version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

# Optional: If you need to configure backend, you can also do it here
backend:
  phases:
    preBuild:
      commands:
        - echo "No backend build process"
