version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building Lambda function...
      - zip -r lambda-function.zip .
artifacts:
  files:
    - lambda-function.zip
